### ISSUE TITLE
'learning resources' post link on repository's main page README leading to 404 error

### ISSUE THREAD

**Issue by hworth** [tamouse/swaac#8]
The link posted on the swaac repository's main page (README file) linking to the "learning resources" post from 2015 currently redirects to a 404 error; it appears the correct link should be github.com/tamouse/swaac/blob/master/posts/2015/05/learning.org

**Comment by tamouse** [comment]
Good heavens, I did not see this, @hworth , my apologies.

**Comment by tamouse** [comment]
@hworth : I've since moved that particular entry up a couple levels, and the README link points to the right place. Thank you for your submission, and again I apologize for not responding sooner.
